import React from "react";
import { Link } from "react-router-dom";

const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/experianscores">ExperianScores</Link>
        </li>
        <li>
          <Link to="/identity">Identity</Link>
        </li>
        <li>
          <Link to="/capital">Capital</Link>
        </li>
        <li>
          <Link to="/reportsexperian">ReportsExperian</Link>
        </li>
        <li>
          <Link to="/experianscoresone">ExperianScoresOne</Link>
        </li>
        <li>
          <Link to="/scoresequifax">ScoresEquifax</Link>
        </li>
        <li>
          <Link to="/reportsequifax">ReportsEquifax</Link>
        </li>
        <li>
          <Link to="/creditcards">Creditcards</Link>
        </li>
        <li>
          <Link to="/ccmarketplace">Ccmarketplace</Link>
        </li>
        <li>
          <Link to="/reportsdb">ReportsDB</Link>
        </li>
        <li>
          <Link to="/businesscapital">Businesscapital</Link>
        </li>
      </ul>
    </div>
  );
};

export default Home;
